#############################################################################
# Makefile for building: QMemory_GUI
# Generated by qmake (2.01a) (Qt 4.8.4) on: Mon Feb 4 19:20:53 2013
# Project:  QMemory_GUI.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile QMemory_GUI.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I../Memory_API -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1,--sort-common,--as-needed,-z,relro
LIBS          = $(SUBLIBS)  -L/usr/lib -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		../Memory_API/src/second_turn.cpp \
		../Memory_API/src/player.cpp \
		../Memory_API/src/game_interface.cpp \
		../Memory_API/src/first_turn.cpp \
		../Memory_API/src/field_implementation.cpp \
		../Memory_API/src/end_turn.cpp \
		../Memory_API/src/card.cpp \
		../Memory_API/src/view.cpp \
		memory_widget.cpp \
		qmemory_state.cpp \
		qmemory_first_turn.cpp \
		qmemory_second_turn.cpp \
		memory_card.cpp moc_mainwindow.cpp \
		moc_memory_widget.cpp \
		moc_qmemory_second_turn.cpp \
		moc_memory_card.cpp
OBJECTS       = main.o \
		mainwindow.o \
		second_turn.o \
		player.o \
		game_interface.o \
		first_turn.o \
		field_implementation.o \
		end_turn.o \
		card.o \
		view.o \
		memory_widget.o \
		qmemory_state.o \
		qmemory_first_turn.o \
		qmemory_second_turn.o \
		memory_card.o \
		moc_mainwindow.o \
		moc_memory_widget.o \
		moc_qmemory_second_turn.o \
		moc_memory_card.o
DIST          = /usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/common/gcc-base.conf \
		/usr/share/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt/mkspecs/common/g++-base.conf \
		/usr/share/qt/mkspecs/common/g++-unix.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		/usr/share/qt/mkspecs/features/debug.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/declarative_debug.prf \
		/usr/share/qt/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/share/qt/mkspecs/features/include_source_dir.prf \
		QMemory_GUI.pro
QMAKE_TARGET  = QMemory_GUI
DESTDIR       = 
TARGET        = QMemory_GUI

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)
	{ test -n "$(DESTDIR)" && DESTDIR="$(DESTDIR)" || DESTDIR=.; } && test $$(gdb --version | sed -e 's,[^0-9]\+\([0-9]\)\.\([0-9]\).*,\1\2,;q') -gt 72 && gdb --nx --batch --quiet -ex 'set confirm off' -ex "save gdb-index $$DESTDIR" -ex quit '$(TARGET)' && test -f $(TARGET).gdb-index && objcopy --add-section '.gdb_index=$(TARGET).gdb-index' --set-section-flags '.gdb_index=readonly' '$(TARGET)' '$(TARGET)' && rm -f $(TARGET).gdb-index || true

Makefile: QMemory_GUI.pro  /usr/share/qt/mkspecs/linux-g++/qmake.conf /usr/share/qt/mkspecs/common/unix.conf \
		/usr/share/qt/mkspecs/common/linux.conf \
		/usr/share/qt/mkspecs/common/gcc-base.conf \
		/usr/share/qt/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt/mkspecs/common/g++-base.conf \
		/usr/share/qt/mkspecs/common/g++-unix.conf \
		/usr/share/qt/mkspecs/qconfig.pri \
		/usr/share/qt/mkspecs/modules/qt_phonon.pri \
		/usr/share/qt/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt/mkspecs/features/qt_functions.prf \
		/usr/share/qt/mkspecs/features/qt_config.prf \
		/usr/share/qt/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt/mkspecs/features/default_pre.prf \
		/usr/share/qt/mkspecs/features/debug.prf \
		/usr/share/qt/mkspecs/features/default_post.prf \
		/usr/share/qt/mkspecs/features/declarative_debug.prf \
		/usr/share/qt/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt/mkspecs/features/warn_on.prf \
		/usr/share/qt/mkspecs/features/qt.prf \
		/usr/share/qt/mkspecs/features/unix/thread.prf \
		/usr/share/qt/mkspecs/features/moc.prf \
		/usr/share/qt/mkspecs/features/resources.prf \
		/usr/share/qt/mkspecs/features/uic.prf \
		/usr/share/qt/mkspecs/features/yacc.prf \
		/usr/share/qt/mkspecs/features/lex.prf \
		/usr/share/qt/mkspecs/features/include_source_dir.prf \
		/usr/lib/libQtGui.prl \
		/usr/lib/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile QMemory_GUI.pro
/usr/share/qt/mkspecs/common/unix.conf:
/usr/share/qt/mkspecs/common/linux.conf:
/usr/share/qt/mkspecs/common/gcc-base.conf:
/usr/share/qt/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt/mkspecs/common/g++-base.conf:
/usr/share/qt/mkspecs/common/g++-unix.conf:
/usr/share/qt/mkspecs/qconfig.pri:
/usr/share/qt/mkspecs/modules/qt_phonon.pri:
/usr/share/qt/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt/mkspecs/features/qt_functions.prf:
/usr/share/qt/mkspecs/features/qt_config.prf:
/usr/share/qt/mkspecs/features/exclusive_builds.prf:
/usr/share/qt/mkspecs/features/default_pre.prf:
/usr/share/qt/mkspecs/features/debug.prf:
/usr/share/qt/mkspecs/features/default_post.prf:
/usr/share/qt/mkspecs/features/declarative_debug.prf:
/usr/share/qt/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt/mkspecs/features/warn_on.prf:
/usr/share/qt/mkspecs/features/qt.prf:
/usr/share/qt/mkspecs/features/unix/thread.prf:
/usr/share/qt/mkspecs/features/moc.prf:
/usr/share/qt/mkspecs/features/resources.prf:
/usr/share/qt/mkspecs/features/uic.prf:
/usr/share/qt/mkspecs/features/yacc.prf:
/usr/share/qt/mkspecs/features/lex.prf:
/usr/share/qt/mkspecs/features/include_source_dir.prf:
/usr/lib/libQtGui.prl:
/usr/lib/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt/mkspecs/linux-g++ CONFIG+=debug CONFIG+=declarative_debug -o Makefile QMemory_GUI.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/QMemory_GUI1.0.0 || $(MKDIR) .tmp/QMemory_GUI1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/QMemory_GUI1.0.0/ && $(COPY_FILE) --parents mainwindow.h ../Memory_API/include/view_state.h ../Memory_API/include/view.h ../Memory_API/include/second_turn.h ../Memory_API/include/player.h ../Memory_API/include/memory_state.h ../Memory_API/include/game_interface.h ../Memory_API/include/first_turn.h ../Memory_API/include/field_implementation.h ../Memory_API/include/end_turn.h ../Memory_API/include/card.h memory_widget.h qmemory_state.h qmemory_first_turn.h qmemory_second_turn.h memory_card.h .tmp/QMemory_GUI1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp ../Memory_API/src/second_turn.cpp ../Memory_API/src/player.cpp ../Memory_API/src/game_interface.cpp ../Memory_API/src/first_turn.cpp ../Memory_API/src/field_implementation.cpp ../Memory_API/src/end_turn.cpp ../Memory_API/src/card.cpp ../Memory_API/src/view.cpp memory_widget.cpp qmemory_state.cpp qmemory_first_turn.cpp qmemory_second_turn.cpp memory_card.cpp .tmp/QMemory_GUI1.0.0/ && $(COPY_FILE) --parents mainwindow.ui .tmp/QMemory_GUI1.0.0/ && (cd `dirname .tmp/QMemory_GUI1.0.0` && $(TAR) QMemory_GUI1.0.0.tar QMemory_GUI1.0.0 && $(COMPRESS) QMemory_GUI1.0.0.tar) && $(MOVE) `dirname .tmp/QMemory_GUI1.0.0`/QMemory_GUI1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/QMemory_GUI1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_memory_widget.cpp moc_qmemory_second_turn.cpp moc_memory_card.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_memory_widget.cpp moc_qmemory_second_turn.cpp moc_memory_card.cpp
moc_mainwindow.cpp: memory_widget.h \
		qmemory_first_turn.h \
		qmemory_state.h \
		qmemory_second_turn.h \
		memory_card.h \
		mainwindow.h
	/usr/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_memory_widget.cpp: qmemory_first_turn.h \
		qmemory_state.h \
		qmemory_second_turn.h \
		memory_card.h \
		memory_widget.h
	/usr/bin/moc $(DEFINES) $(INCPATH) memory_widget.h -o moc_memory_widget.cpp

moc_qmemory_second_turn.cpp: qmemory_state.h \
		qmemory_second_turn.h
	/usr/bin/moc $(DEFINES) $(INCPATH) qmemory_second_turn.h -o moc_qmemory_second_turn.cpp

moc_memory_card.cpp: memory_card.h
	/usr/bin/moc $(DEFINES) $(INCPATH) memory_card.h -o moc_memory_card.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h
ui_mainwindow.h: mainwindow.ui
	/usr/bin/uic mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		memory_widget.h \
		qmemory_first_turn.h \
		qmemory_state.h \
		qmemory_second_turn.h \
		memory_card.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		memory_widget.h \
		qmemory_first_turn.h \
		qmemory_state.h \
		qmemory_second_turn.h \
		memory_card.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

second_turn.o: ../Memory_API/src/second_turn.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o second_turn.o ../Memory_API/src/second_turn.cpp

player.o: ../Memory_API/src/player.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o player.o ../Memory_API/src/player.cpp

game_interface.o: ../Memory_API/src/game_interface.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o game_interface.o ../Memory_API/src/game_interface.cpp

first_turn.o: ../Memory_API/src/first_turn.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o first_turn.o ../Memory_API/src/first_turn.cpp

field_implementation.o: ../Memory_API/src/field_implementation.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o field_implementation.o ../Memory_API/src/field_implementation.cpp

end_turn.o: ../Memory_API/src/end_turn.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o end_turn.o ../Memory_API/src/end_turn.cpp

card.o: ../Memory_API/src/card.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o card.o ../Memory_API/src/card.cpp

view.o: ../Memory_API/src/view.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o view.o ../Memory_API/src/view.cpp

memory_widget.o: memory_widget.cpp memory_widget.h \
		qmemory_first_turn.h \
		qmemory_state.h \
		qmemory_second_turn.h \
		memory_card.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o memory_widget.o memory_widget.cpp

qmemory_state.o: qmemory_state.cpp qmemory_state.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qmemory_state.o qmemory_state.cpp

qmemory_first_turn.o: qmemory_first_turn.cpp qmemory_first_turn.h \
		qmemory_state.h \
		memory_widget.h \
		qmemory_second_turn.h \
		memory_card.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qmemory_first_turn.o qmemory_first_turn.cpp

qmemory_second_turn.o: qmemory_second_turn.cpp qmemory_second_turn.h \
		qmemory_state.h \
		memory_widget.h \
		qmemory_first_turn.h \
		memory_card.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qmemory_second_turn.o qmemory_second_turn.cpp

memory_card.o: memory_card.cpp memory_card.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o memory_card.o memory_card.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_memory_widget.o: moc_memory_widget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_memory_widget.o moc_memory_widget.cpp

moc_qmemory_second_turn.o: moc_qmemory_second_turn.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_qmemory_second_turn.o moc_qmemory_second_turn.cpp

moc_memory_card.o: moc_memory_card.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_memory_card.o moc_memory_card.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

